In [2]:
# Step 1: Library
import numpy as np
from scipy.linalg import svd

In [13]:
A = np.array(
    [
        [1.01, 0.9, 0.2, 1.001, 0.3],
        [0.2, 1.01, 0.3, 0.8, 0.4],
        [1, 1.002, 2, 0.98, 2],
        [0.3, 2, 0.4, 1.01, 0.9],
        [1.1, 0.2, 0.03, 2, 0.87],
    ]
)
print(A)

# Step 1: Construct SVD
U, S, Vt = svd(A)

# Step 2: Find minimum k such that >= 90% info retained
target_info_retained = 0.90  # 90%
I_retained = np.cumsum(S**2) / np.sum(S**2)
k_lambda = np.argmax(I_retained >= target_info_retained) + 1

print("Singular values:", np.round(S, 6))
print("Cumulative info retained:", np.round(I_retained, 4))
print("Chosen kλ =", k_lambda)

# Step 3, 4, 5: Build truncated SVD
U_k = U[:, :k_lambda]  # m x k
S_k = np.diag(S[:k_lambda])  # k x k
V_k = Vt[:k_lambda, :]  # k x n

# Step 6: Reconstruction
A_k = U_k @ S_k @ V_k

# Step 7: % info retained
info_retained = (np.sum(S[:k_lambda] ** 2) / np.sum(S**2)) * 100

print(f"Matrix U_k:\n{np.round(U_k, 4)}\n")
print(f"Matrix Σ_k:\n{np.round(S_k, 4)}\n")
print(f"Matrix V_k^T:\n{np.round(V_k, 4)}\n")
print(f"Reconstructed A_k (approx):\n{np.round(A_k, 4)}\n")
print(f"Information retained: {info_retained:.2f}%")

[[1.01  0.9   0.2   1.001 0.3  ]
 [0.2   1.01  0.3   0.8   0.4  ]
 [1.    1.002 2.    0.98  2.   ]
 [0.3   2.    0.4   1.01  0.9  ]
 [1.1   0.2   0.03  2.    0.87 ]]
Singular values: [4.681907 1.793252 1.57961  0.549034 0.178596]
Cumulative info retained: [0.7839 0.8989 0.9881 0.9989 1.    ]
Chosen kλ = 3
Matrix U_k:
[[-0.3281  0.3293 -0.0878]
 [-0.2737  0.0912 -0.315 ]
 [-0.6482 -0.6587  0.3795]
 [-0.4661  0.0207 -0.7192]
 [-0.4243  0.67    0.4814]]

Matrix Σ_k:
[[4.6819 0.     0.    ]
 [0.     1.7933 0.    ]
 [0.     0.     1.5796]]

Matrix V_k^T:
[[-0.3505 -0.4781 -0.351  -0.5344 -0.4897]
 [ 0.2427 -0.0536 -0.6669  0.6234 -0.3238]
 [ 0.3429 -0.8604  0.2366  0.17    0.2395]]

Reconstructed A_k (approx):
[[0.6342 0.8222 0.1126 1.1656 0.528 ]
 [0.3183 1.0321 0.223  0.7023 0.4555]
 [0.9824 0.9983 1.9947 0.9872 2.0122]
 [0.3843 2.0187 0.4723 0.9962 0.7846]
 [1.2487 0.2311 0.0759 1.9399 0.766 ]]

Information retained: 98.81%
