# Exercise 1 - Singular Value Decomposition (SVD) 

A = U × Σ × V^T

Where:
- **A** is our original matrix (4×5 in this example)
- **U** is an orthogonal matrix containing the left singular vectors
- **Σ** (Sigma) is a diagonal matrix containing the singular values
- **V^T** is the transpose of an orthogonal matrix containing the right singular vectors


In [1]:
# Step 1: Library
import numpy as np
from scipy.linalg import svd

In [8]:
# Step 2: Define the matrix A
A = np.array(
    [
        [1, 0, 0, 0, 2],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
    ]
)

print(f"Matrix A:\n{A}\n")

# Step 3: Compute SVD
U, S_diag, Vt = svd(A)

# Step 4: Convert singular values vector into a diagonal matrix Σ
# 4.1 and 4.3 Create a zero matrix Σ with the same shape as A
Sigma = np.zeros_like(A, dtype=float)
# 4.2 Fill the diagonal of Σ with the singular values
np.fill_diagonal(Sigma, S_diag)

print(f"Matrix U:\n{U}\n")
print(f"Singular values:\n{S_diag}\n")
print(f"Matrix Σ (Sigma):\n{Sigma}\n")
print(f"Matrix V^T:\n{Vt}\n")

# Step 5: Verify decomposition
A_reconstructed = U @ Sigma @ Vt
print(f"Reconstructed A (from UΣV^T):\n{A_reconstructed}\n")
print(np.round(A_reconstructed, 5))

Matrix A:
[[1 0 0 0 2]
 [0 0 3 0 0]
 [0 0 0 0 0]
 [0 2 0 0 0]]

Matrix U:
[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]]

Singular values:
[3.         2.23606798 2.         0.        ]

Matrix Σ (Sigma):
[[3.         0.         0.         0.         0.        ]
 [0.         2.23606798 0.         0.         0.        ]
 [0.         0.         2.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]]

Matrix V^T:
[[-0.          0.          1.         -0.          0.        ]
 [ 0.4472136   0.          0.          0.          0.89442719]
 [-0.          1.          0.         -0.          0.        ]
 [ 0.          0.          0.          1.          0.        ]
 [-0.89442719  0.          0.          0.          0.4472136 ]]

Reconstructed A (from UΣV^T):
[[1. 0. 0. 0. 2.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]]

[[1. 0. 0. 0. 2.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]]
