In [2]:
# Step 1: Library
import numpy as np
from scipy.linalg import svd

In [13]:
# Step 1: Compute SVD
A = np.array(
    [
        [1.01, 0.9, 0.2, 1.001, 0.3],
        [0.2, 1.01, 0.3, 0.8, 0.4],
        [1, 1.002, 2, 0.98, 2],
        [0.3, 2, 0.4, 1.01, 0.9],
        [1.1, 0.2, 0.03, 2, 0.87],
    ]
)

U, S, Vt = svd(A)

# Step 2: Truncate to keep only top k=4 singular values
k = 4
S_k = np.diag(S[:k])  # k x k Sigma_k

# Step 3: Construct U_k with k=4 columns
U_k = U[:, :k]  # m x k

# Step 4: Construct V_kt with k=4 rows
V_kt = Vt[:k, :]  # k x n


# Step 5: Compute information retained
retain_percent = (np.sum(S[:k] ** 2) / np.sum(S**2)) * 100
print(f"Information retained: {retain_percent:.2f}%")

# Step 6: Print results
print(f"\nMatrix U_k:\n{U_k}\n")
print(f"\nMatrix Σ_k:\n{S_k}\n")
print(f"\nMatrix V_k^T:\n{V_kt}\n")

# Step 7: Reconstruct truncated A
A_trunc = U_k @ S_k @ V_kt

print(f"\nTruncated Reconstruction A_k:\n{np.round(A_trunc, 4)}\n")

Information retained: 99.89%

Matrix U_k:
[[-0.32813554  0.32928789 -0.08780746  0.88098834]
 [-0.27374756  0.09123211 -0.31504405 -0.16061502]
 [-0.64816455 -0.65873014  0.3795124   0.04270121]
 [-0.46609071  0.0207275  -0.71918456 -0.25646457]
 [-0.4243012   0.66999341  0.4814364  -0.36119923]]


Matrix Σ_k:
[[4.68190663 0.         0.         0.        ]
 [0.         1.79325215 0.         0.        ]
 [0.         0.         1.57960998 0.        ]
 [0.         0.         0.         0.54903356]]


Matrix V_k^T:
[[-0.35047463 -0.4780765  -0.35097791 -0.5344013  -0.48973477]
 [ 0.24274782 -0.05358443 -0.66685673  0.62343097 -0.32378718]
 [ 0.3428965  -0.86035897  0.23658964  0.1699711   0.2394569 ]
 [ 0.77612359  0.16080247  0.18212689 -0.3391472  -0.47284639]]


Truncated Reconstruction A_k:
[[1.0096 0.8999 0.2007 1.0015 0.2993]
 [0.2498 1.0179 0.2069 0.7322 0.4972]
 [1.0006 1.0021 1.9989 0.9792 2.0011]
 [0.275  1.996  0.4467 1.044  0.8512]
 [1.0947 0.1992 0.0398 2.0072 0.8597]]

