# Exercise 2 - Singular Value Decomposition (SVD) Explanation


## Key Concepts
- **Singular Values**: The diagonal elements of \( \Sigma \), often denoted as \( \sigma_1, \sigma_2, \dots \), represent the importance of each dimension.
- **Rank**: The number of non-zero singular values indicates the rank of the matrix.
- **Compact SVD**: For a matrix of rank \( r \), we can reduce to \( U_r \) (\( m \times r \)), \( \Sigma_r \) (\( r \times r \)), and \( V_r^T \) (\( r \times n \)), which is more efficient for storage and computation.

## Workflow in This Notebook
1. **Import Libraries**: Load necessary modules like NumPy and SciPy's SVD function.
2. **Define Matrix**: Create the input matrix \( A \).
3. **Perform Full SVD**: Decompose \( A \) into \( U \), \( \Sigma \), and \( V^T \).
4. **Determine Rank**: Count non-zero singular values using a tolerance to handle floating-point errors.
5. **Construct Compact SVD**: Extract the top \( r \) components for efficiency.
6. **Display Results**: Print the compact matrices.
7. **Verify Reconstruction**: Reconstruct \( A \) from the compact SVD and compare with the original.

This process helps in applications like dimensionality reduction, data compression, and solving linear systems. The code uses NumPy for array operations and SciPy for the SVD computation.

In [1]:
# Step 1: Library
import numpy as np
from scipy.linalg import svd

In [21]:
A = np.array(
    [
        [1, 0, 0, 0, 2],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
    ]
)

# Step 1: Full SVD
U, S_diag, Vt = svd(A)

# Step 2: Find rank r by counting how many singular values λ that are not 0
tol = 1e-10  # use this tolerance to avoid python computation floating point error
r = np.count_nonzero(np.abs(S_diag) > tol)
print(f"Number of non-zero singular values (λ): {r}\n")

# Step 3: Construct compact SVD components
S_r = np.diag(S_diag[:r])  # r x r diagonal matrix

# Step 4: Construct first r columns of U to create U_r
U_r = U[:, :r]

# Step 5: Construct first r rows of V^T to create V_r^T
V_rt = Vt[:r, :]

# Step 6: Display results
print(f"Compact U_r:\n{U_r}\n")
print(f"Compact Σ_r:\n{S_r}\n")
print(f"Compact V_r^T:\n{V_rt}\n")

# Step 7: Verify reconstruction
A_reconstructed = U_r @ S_r @ V_rt
print(f"Reconstructed A (from compact SVD):\n{np.round(A_reconstructed, 5)}\n")

Number of non-zero singular values (λ): 3

Compact U_r:
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]]

Compact Σ_r:
[[3.         0.         0.        ]
 [0.         2.23606798 0.        ]
 [0.         0.         2.        ]]

Compact V_r^T:
[[-0.          0.          1.         -0.          0.        ]
 [ 0.4472136   0.          0.          0.          0.89442719]
 [-0.          1.          0.         -0.          0.        ]]

Reconstructed A (from compact SVD):
[[1. 0. 0. 0. 2.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]]

