In [1]:
# Step 1: Library
import numpy as np
from scipy.linalg import svd

In [21]:
A = np.array(
    [
        [1, 0, 0, 0, 2],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
    ]
)

# Step 1: Full SVD
U, S_diag, Vt = svd(A)

# Step 2: Find rank r by counting how many singular values λ that are not 0
tol = 1e-10  # use this tolerance to avoid python computation floating point error
r = np.count_nonzero(np.abs(S_diag) > tol)
print(f"Number of non-zero singular values (λ): {r}\n")

# Step 3: Construct compact SVD components
S_r = np.diag(S_diag[:r])  # r x r diagonal matrix

# Step 4: Construct first r columns of U to create U_r
U_r = U[:, :r]

# Step 5: Construct first r rows of V^T to create V_r^T
V_rt = Vt[:r, :]

# Step 6: Display results
print(f"Compact U_r:\n{U_r}\n")
print(f"Compact Σ_r:\n{S_r}\n")
print(f"Compact V_r^T:\n{V_rt}\n")

# Step 7: Verify reconstruction
A_reconstructed = U_r @ S_r @ V_rt
print(f"Reconstructed A (from compact SVD):\n{np.round(A_reconstructed, 5)}\n")

Number of non-zero singular values (λ): 3

Compact U_r:
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]]

Compact Σ_r:
[[3.         0.         0.        ]
 [0.         2.23606798 0.        ]
 [0.         0.         2.        ]]

Compact V_r^T:
[[-0.          0.          1.         -0.          0.        ]
 [ 0.4472136   0.          0.          0.          0.89442719]
 [-0.          1.          0.         -0.          0.        ]]

Reconstructed A (from compact SVD):
[[1. 0. 0. 0. 2.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]]

