In [1]:
import numpy as np

x_1 = [1,2,3]
x_2 = [4,5,6]
x_3 = [9,8,7]

# Mean normalisation
x_1 = (x_1 - np.mean(x_1)) / (np.max(x_1) - np.min(x_1))
x_2 = (x_2 - np.mean(x_2)) / (np.max(x_2) - np.min(x_2))
x_3 = (x_3 - np.mean(x_3)) / (np.max(x_3) - np.min(x_3))

print(x_1)
print(x_2)
print(x_3)

[-0.5  0.   0.5]
[-0.5  0.   0.5]
[ 0.5  0.  -0.5]


In [2]:
# Min-max scaling
x_1_min_max = (x_1 - np.min(x_1)) / (np.max(x_1) - np.min(x_1))
x_2_min_max = (x_2 - np.min(x_2)) / (np.max(x_2) - np.min(x_2))
x_3_min_max = (x_3 - np.min(x_3)) / (np.max(x_3) - np.min(x_3))

print(x_1_min_max)
print(x_2_min_max)
print(x_3_min_max)

[0.  0.5 1. ]
[0.  0.5 1. ]
[1.  0.5 0. ]


In [9]:
import math

# Unit vector scaling
x_1_unit_vector = x_1 / np.linalg.norm(x_1)
x_2_unit_vector = x_2 / np.linalg.norm(x_2)
x_3_unit_vector = x_3 / np.linalg.norm(x_3)

print(x_1_unit_vector)
print(x_2_unit_vector)
print(x_3_unit_vector)



[-0.70710678  0.          0.70710678]
[-0.70710678  0.          0.70710678]
[ 0.70710678  0.         -0.70710678]
