In [1]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torch.optim import Adam

# Visualization tools
import torchvision
import torchvision.transforms.v2 as transforms
import torchvision.transforms.functional as F
import matplotlib.pyplot as plt

In [2]:
transform = transforms.Compose(
    [transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))]
)

/Users/khangnghiem/Library/CloudStorage/GoogleDrive-khangnghiem@gmail.com/My Drive/learn/.venv/lib/python3.12/site-packages/torchvision/transforms/v2/_deprecated.py:42: UserWarning: The transform `ToTensor()` is deprecated and will be removed in a future release. Instead, please use `v2.Compose([v2.ToImage(), v2.ToDtype(torch.float32, scale=True)])`.Output is equivalent up to float precision.
  warnings.warn(


In [6]:
train_set = torchvision.datasets.MNIST("data", download=True)
train_set

Dataset MNIST
    Number of datapoints: 60000
    Root location: data
    Split: Train

In [41]:
test = torch.rand(1, 4)
print(test)
test.apply_(lambda x: x * 2)

tensor([[0.5179, 0.4363, 0.7745, 0.4363]])


tensor([[1.0359, 0.8725, 1.5491, 0.8726]])

In [48]:
torch.rand(3)

tensor([0.9950, 0.3856, 0.1652])

In [6]:
train_set = torchvision.datasets.MNIST("data", download=True, transform=transform)
train_set

/Users/khangnghiem/Library/CloudStorage/GoogleDrive-khangnghiem@gmail.com/My Drive/learn/.venv/lib/python3.12/site-packages/torchvision/transforms/v2/_deprecated.py:42: UserWarning: The transform `ToTensor()` is deprecated and will be removed in a future release. Instead, please use `v2.Compose([v2.ToImage(), v2.ToDtype(torch.float32, scale=True)])`.Output is equivalent up to float precision.
  warnings.warn(


Dataset MNIST
    Number of datapoints: 60000
    Root location: data
    Split: Train
    StandardTransform
Transform: Compose(
                 ToTensor()
                 Normalize(mean=[0.5], std=[0.5], inplace=False)
           )